### ISSUE TITLE
bsub email address configurable?

### ISSUE THREAD

**Issue by obigriffith** [genome/gms#67] opened 2014-01-13 05:02 UTC
When I start a new build on stand-alone box bsub infers my email address to be $user_name at genome.wustl.edu. Are any emails actually sent to these addresses?  And, can we configure this so that a user can have a correct email address?

genome model build start "name='hcc1395-somatic-exome'"
'models' may require verification...
Resolving parameter 'models' from command argument 'name='hcc1395-somatic-exome''... found 1
Trying to start #1: hcc1395-somatic-exome (2891407507)...
*************\* bsub -N -H -P build67178afc98d94370a7f2209a3a334284 -q normal  -u obig@genome.wustl.edu -o /opt/gms/LNXE927/fs/LNXE927/info/model_data/2891407507/build67178afc98d94370a7f2209a3a334284/logs/workflow-server.out -e /opt/gms/LNXE927/fs/LNXE927/info/model_data/2891407507/build67178afc98d94370a7f2209a3a334284/logs/workflow-server.err " annotate-log genome model services build run  --model-id 2891407507 --build-id 67178afc98d94370a7f2209a3a334284 1>/opt/gms/LNXE927/fs/LNXE927/info/model_data/2891407507/build67178afc98d94370a7f2209a3a334284/logs/workflow-server.out 2>/opt/gms/LNXE927/fs/LNXE927/info/model_data/2891407507/build67178afc98d94370a7f2209a3a334284/logs/workflow-server.err " ***********
Successfully started build (67178afc98d94370a7f2209a3a334284 of hcc1395-somatic-exome).
Build IDs: 67178afc98d94370a7f2209a3a334284

**Comment by gatoravi** [comment] 2014-01-13 20:07
From Scott:

I'd suggest we:
- add GENOME_SYS_EMAIL_DOMAIN 
- make Genome::Sys->user_email()
- implement it to look at the environment variable to return the email address based on it
- switch code to lean on that method
- tell the user to edit /etc/genome.conf to set the env value
- default to the DNS mx record for the current domain if it is set at install time

**Comment by jeldred** [comment] 2014-01-13 20:21
At a glance, does this appear to overlap with the work done here?

https://jira.gsc.wustl.edu/browse/AR-294

Jim

On Jan 13, 2014, at 2:07 PM, Avinash Ramu wrote:

> From Scott:
> 
> I'd suggest we:
> 
> add GENOME_SYS_EMAIL_DOMAIN
> make Genome::Sys->user_email()
> implement it to look at the environment variable to return the email address based on it
> switch code to lean on that method
> tell the user to edit /etc/genome.conf to set the env value
> default to the DNS mx record for the current domain if it is set at install time
> —
> Reply to this email directly or view it on GitHub.

---

This email message is a private communication. The information transmitted, including attachments, is intended only for the person or entity to which it is addressed and may contain confidential, privileged, and/or proprietary material. Any review, duplication, retransmission, distribution, or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is unauthorized by the sender and is prohibited. If you have received this message in error, please contact the sender immediately by return email and delete the original message from all computer systems. Thank you.

**Comment by gatoravi** [comment] 2014-01-27 17:17
The email address for the lsf jobs is set in Genome/Model/Build.pm

```
   1452         my $user = Genome::Sys->username;
   1453         my $lsf_command  = join(' ',
   1454             'bsub -N -H',
   1455             '-P', $lsf_project,
   1456             '-q', $server_dispatch,   1457             ($ENV{WF_EXCLUDE_JOB_GROUP} ? '' : $job_group_spec),
   1458             '-u', $user . '@genome.wustl.edu',   1459             '-o', $build_event->output_log_file,
   1460             '-e', $build_event->error_log_file,
   1461             '"',
   1462               'annotate-log',
   1463               ($Command::entry_point_bin || 'genome'),
   1464               'model services build run',
   1465               $add_args,
   1466               '--model-id', $model->id,
   1467               '--build-id', $self->id,
   1468               "1>" . $build_event->output_log_file,
   1469               "2>" . $build_event->error_log_file,
   1470             '"'
   1471         );
```

We need to incorporate Scott's suggestion above and use that email address here. We could either let the user set a domain or the user could set the entire email address. 

If we go the domain way we will use Scott's approach, 
GENOME_SYS_EMAIL_DOMAIN = someuniv.edu
and the username is obtained from the user's unix userid.

if we decide to use an email address instead then,
GENOME_SYS_EMAIL_ADDRESS = john.doe@gmail.com and email from lsf goes there. 

Trying to figure out how @amb43790 changes in Master can be incorporated here.

**Comment by gatoravi** [comment] 2014-01-28 15:36
effort on this issue has been started here https://github.com/genome/gms-core/commit/8cdf36c74f5071675d44ad78fd6de1d7d260cdd8

The gms user can set GMS_USER_EMAIL  in /etc/genome.conf to  a valid email address if they wish to set a specific email address to receive report emails. By default this is set to gmsuser@example.com. 

If an organization decides to go the domain way, they need to change the GENOME_EMAIL_DOMAIN to the domain that the organization uses. Within TGI this variable is set to 'genome.wustl.edu'. By default, on the standalone, this is set to 'localhost'

Looks like right now the mail server that is being used can only send mail to TGI email addresses, this needs to be configured in a way to allow outside email addresses.

**Comment by gatoravi** [comment] 2014-01-28 15:55
The mail server seems to be set in Genome/Report/Email.pm

``` perl
  while ($count++ < $tries and !$success)  {
    64         eval {
    65             my $sender = Mail::Sender->new({
    66                     smtp => 'gscsmtp.wustl.edu',
    67                     to => $to,
    68                     from => $from,
    69                     replyto => $reply_to,
    70                     subject => Genome::Utility::Text::capitalize_words( $report->description ),
    71                     multipart => 'related',
    72                     on_errors => 'die',
    73                 }) or die "Can't create Mail::Sender";
```

We should use an alternative smtp server.

**Comment by ghost** [comment] 2014-01-28 20:53
Here is a code example which converts from an email domain name like genome.wustl.edu to the smtp host for that domain (ie, gscsmtp.wustl.edu) by looking up the DNS MX record.  I'm not completely convinced this is what we want to do, but I'm sticking this code snippet here just in case we want it later.

``` perl
#!/usr/bin/env genome-perl

use strict;
use warnings FATAL => qw(all);

use Net::DNS qw(mx);

print map {$_->exchange ."\n"} mx("genome.wustl.edu");
```

**Comment by brummett** [comment] 2014-01-28 22:50
When I made all these env vars, GENOME_EMAIL_SMTP_SERVER was intended to
fill this role.  It's possible I didn't find and replace all the
occurrences.

At the time, all these GENOME_EMAIL_SMTP_SERVER was set in
Genome::Site::TGI and ::Clia.  In the production GMS, these vars are now
set from one of the login scripts.

**Comment by gatoravi** [comment] 2014-02-05 22:42
Further work on this issue was done here https://github.com/genome/gms/commit/dd9cc4d510fbf7880fcfaeffc646918df676f426 and 
https://github.com/genome/gms-core/commit/f3e3b877531a024c43c2f03c791d87461cb837bb.

We now use the GENOME_EMAIL_SMTP_SERVER environment variable, this variable is set to `hostname` during the GMS install. We now install a mail-server (Exim) with the name `hostname`. LSF job reports are sent using this server. This mail-server seems to be able to send email addresses to all public-domain email addresses but not to domains like wustl.edu(this needs to be investigated, maybe related to @mkiwala-g 's post above).

To change the email address where the LSF email addresses are sent to, the user needs to change the GENOME_USER_EMAIL environment variable in /etc/genome.conf

sidenote - We need to document all these environment variables in one place so that the end-user can customize the system according to his/her needs.

**Comment by malachig** [comment] 2014-03-31 21:02
I believe this issue is now resolved.  If the user sets `GENOME_USER_EMAIL` to a valid email address and the local network allows outgoing emails, LSF reports will go there.  Closing the issue.

**Closed as completed by malachig** 2014-03-31 21:02 UTC
Labels: enhancement
