### ISSUE TITLE
gms-pub branch no longer compiles

### ISSUE THREAD

**Issue by GrubLord** [genome/gms#200] opened 2016-01-15 03:41 UTC
Having trouble compiling a new clean install of gms... somehow, the software refuses to compile.

I'm not aware of these branches having changed since last we did this, so it seems like unusual behaviour...

We'd appreciate any help with diagnosing the error. It appears to be a compile error related to a closed, past issue.

```
sudo bash -l -c 'source /etc/genome.conf; /usr/bin/perl setup/prime-disk-allocations.pl'
setting GENOME_* variables...
updating PATH, PERL5LIB, and CLASSPATH for the GMS
configuring tab-completion...
Can't locate Mouse.pm in @INC (@INC contains: /opt/gms/II26B153/sw/ur/lib /opt/gms/II26B153/sw/workflow/lib /opt/gms/II26B153/sw/genome/lib/perl/x86_64-linux-gnu-thread-multi /opt/gms/II26B153/sw/genome/lib/perl /opt/gms/II26B153/sw/genome/lib/perl-added /usr/lib/perl5/x86_64-linux-gnu-thread-multi /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14.2 /usr/share/perl/5.14.2 /usr/local/lib/site_perl /home/ubuntu/gms) at /opt/gms/II26B153/sw/genome/lib/perl/Genome/Sys/Lock/FileBackend.pm line 17.
BEGIN failed--compilation aborted at /opt/gms/II26B153/sw/genome/lib/perl/Genome/Sys/Lock/FileBackend.pm line 17.
Compilation failed in require at /opt/gms/II26B153/sw/genome/lib/perl/Genome/Site/SGMS.pm line 12.
Compilation failed in require at /usr/share/perl/5.14.2/Module/Runtime.pm line 317.
BEGIN failed--compilation aborted at /opt/gms/II26B153/sw/genome/lib/perl/Genome/Site.pm line 49.
Compilation failed in require at /opt/gms/II26B153/sw/genome/lib/perl/Genome.pm line 24.
Compilation failed in require at setup/prime-disk-allocations.pl line 4.
BEGIN failed--compilation aborted at setup/prime-disk-allocations.pl line 4.
No backends registered for scope 'site' at /opt/gms/II26B153/sw/genome/lib/perl/Genome/Sys/Lock.pm line 201
    Genome::Sys::Lock::backends('site') called at /opt/gms/II26B153/sw/genome/lib/perl/Genome/Sys/Lock.pm line 171
    Genome::Sys::Lock::release_all() called at /opt/gms/II26B153/sw/genome/lib/perl/Genome/Sys/Lock.pm line 263
    Genome::Sys::Lock::END() called at setup/prime-disk-allocations.pl line 4
    eval {...} called at setup/prime-disk-allocations.pl line 4
END failed--call queue aborted at setup/prime-disk-allocations.pl line 4.
make: *** [done-host/db-schema] Error 22
make[1]: *** [setup] Error 2
rm done-repo/download-apt-mirror-min-ubuntu-12.04-2015.04.09.tgz done-repo/download-java-2013-08-27.tgz
make[1]: Leaving directory `/home/ubuntu/gms'
make: *** [all] Error 2
```

We've also tried switching the branches specified in the Makefile to "master", in case recent code changes might have fixed whatever the issue is... but we are getting the exact same error.

Thanks in advance for any help you can offer.

**Comment by gatoravi** [comment] 2016-01-15 16:36
This is a duplicate of #162, closing.

**Closed as completed by gatoravi** 2016-01-15 16:36 UTC
